---
title: "OTU Table Comparison"
author: "Alicia Halhed"
date: "26/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd("~/OneDrive - University of Guelph/Alicia's Thesis/red-squirrel-w2020/R-env")
library(tidyverse)
```

## Load in the files

```{r}
# published
OTU_published <- read.table("~/OneDrive - University of Guelph/Alicia's Thesis/red-squirrel-data/exploration/otu_table_all_samplesAH.txt", 
                            sep="\t", header = TRUE, row.names = "ID") #%>%
  select(-taxonomy)
rownames(OTU_published) <- c()
```

```{bash}
# unzip the qza for the OTU table
cd ./OneDrive\ -\ University\ of\ Guelph/Alicia\'s\ Thesis/red-squirrel-w2020/
unzip OTU-table-dn-99.qza
# move the OTU table into the current working directory
mv ./32484b65-81c9-4517-851f-6e5135fb0233/data/feature-table.biom ./R-env/
# delete the unzipped directory
rm -r ./32484b65-81c9-4517-851f-6e5135fb0233/
# convert the biom file to a text file
biom convert -i feature-table.biom -o ./R-env/feature-table.txt --to-tsv
```

```{r}
# mine
OTU_mine <- read.table("~/OneDrive - University of Guelph/Alicia's Thesis/red-squirrel-w2020/R-env/feature-table.txt", 
                            sep="\t", header = TRUE, row.names = "OTU") %>% 
  select(colnames(OTU_published)) %>% # select only the samples retained in the original data
  .[ rowSums(.)!=0, ] # get rid of OTUs with no observations
rownames(OTU_mine) <- c()
```

```{r}
OTU_joined <- OTU_mine[1:nrow(OTU_published),] %>% # trim my otu table to the length of the published one
  rename_all(paste0, "_mine") %>%
  cbind(., OTU_published %>% rename_all(paste0, "_published"))
```

