#---
#title: "Significant Ordisurf Plots - By Month"
#author: "Alicia Halhed"
#date: "04/22/2020"
#---

print("Set up (working directory, theme, and packages)")
# set working directory
setwd("/home/ahalhed/red-squirrel-w2020/R-env")

# attach required packages
library(tidyverse)
library(qiime2R)
library(phyloseq)
library(vegan)

# set theme for plots
theme_set(theme_bw())

print("Initiate functions for analysis")
# subset the XY's by grid and year
XY_year <- function(metadata, grid, year) {
  df1 <- subset(metadata, Grid == grid, 
                select = c("SampleID", "Location X", "Location Y", "Year"))
  df2 <- subset(df1, Year == year, 
                select = c("SampleID", "Location X", "Location Y"))
  df3 <- column_to_rownames(remove_rownames(df2), var = "SampleID")
  return(df3)
}

# get the data
print("Read in the Data")
print("Read in the metadata")
rs_q2_metadata <- read.table("/home/ahalhed/red-squirrel-w2020/input/RS_meta.tsv", sep="\t")
colnames(rs_q2_metadata) <- c("SampleID", "Grid", "Location X", "Location Y", "Sex", "Age", "Month", "Season", "Year", "Squirrel.ID", "SireID", "DamID", "CollectionDate", "FoodSupplement", "BirthYear", "Location", "Date")

# start analysis
print("Starting initial data preparation")
print("Access XY data")
XY_AG <- XY_year(rs_q2_metadata, "AG", 2008)
XY_CH <- XY_year(rs_q2_metadata, "CH", 2008)
XY_JO <- XY_year(rs_q2_metadata, "JO", 2008)
XY_KL8 <- XY_year(rs_q2_metadata, "KL", 2008)
XY_KL9 <- XY_year(rs_q2_metadata, "KL", 2009)
XY_KL10 <- XY_year(rs_q2_metadata, "KL", 2010)
XY_LL <- XY_year(rs_q2_metadata, "LL", 2008)
XY_SU <- XY_year(rs_q2_metadata, "SU", 2008)

print("Computing Euclidean Distances")
d_AG <- dist(XY_AG)
d_CH <- dist(XY_CH)
d_JO <- dist(XY_JO)
d_KL8 <- dist(XY_KL8)
d_KL9 <- dist(XY_KL9)
d_KL10 <- dist(XY_KL10)
d_LL <- dist(XY_LL)
d_SU <- dist(XY_SU)


# Remove objects we're done with
print("Removing full metadata data frame")
rm(rs_q2_metadata)

# unweighted PCNM
print("Unweighted PCNM")
AG <- pcnm(d_AG)
CH <- pcnm(d_CH)
JO <- pcnm(d_JO)
KL8 <- pcnm(d_KL8)
KL9 <- pcnm(d_KL9)
KL10 <- pcnm(d_KL10)
LL <- pcnm(d_LL)
SU <- pcnm(d_SU)

# plot with ordisurf
print("Plotting significant PCNM axes with ordisurf")
# replace grid-year with values used in this script
print("Core")
print("AG 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_AG2008_ordiSIG.pdf")
ordisurf(XY_AG, scores(AG, choi=4), bubble = 4, main = "PCNM 4 (May)")
par(mfrow=c(2,2))
ordisurf(XY_AG, scores(AG, choi=1), bubble = 4, main = "PCNM 1 (July)")
ordisurf(XY_AG, scores(AG, choi=6), bubble = 4, main = "PCNM 6 (July)")
ordisurf(XY_AG, scores(AG, choi=36), bubble = 4, main = "PCNM 36 (July)")
dev.off()

print("CH 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_CH2008_ordiSIG.pdf")
ordisurf(XY_CH, scores(CH, choi=1), bubble = 4, main = "PCNM 1 (April)")
dev.off()

print("JO 2008")
print("No significant core axes")

print("KL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_KL2008_ordiSIG.pdf")
par(mfrow=c(2,3))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (May)")
ordisurf(XY_KL8, scores(KL8, choi=10), bubble = 4, main = "PCNM 10 (May)")
ordisurf(XY_KL8, scores(KL8, choi=13), bubble = 4, main = "PCNM 13 (May)")
ordisurf(XY_KL8, scores(KL8, choi=18), bubble = 4, main = "PCNM 18 (May)")
ordisurf(XY_KL8, scores(KL8, choi=36), bubble = 4, main = "PCNM 36 (May)")
par(mfrow=c(1,1))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (June)")
par(mfrow=c(1,2))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (August)")
ordisurf(XY_KL8, scores(KL8, choi=12), bubble = 4, main = "PCNM 12 (August)")
dev.off()

print("KL 2009")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_KL2009_ordiSIG.pdf")
ordisurf(XY_KL9, scores(KL9, choi=4), bubble = 4, main = "PCNM 4 (August)")
dev.off()

print("KL 2010")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_KL2010_ordiSIG.pdf")
ordisurf(XY_KL10, scores(KL10, choi=12), bubble = 4, main = "PCNM 12 (February)")
par(mfrow=c(2,2))
ordisurf(XY_KL10, scores(KL10, choi=2), bubble = 4, main = "PCNM 2 (March)")
ordisurf(XY_KL10, scores(KL10, choi=5), bubble = 4, main = "PCNM 5 (March)")
ordisurf(XY_KL10, scores(KL10, choi=22), bubble = 4, main = "PCNM 22 (March)")
par(mfrow=c(2,2))
ordisurf(XY_KL10, scores(KL10, choi=7), bubble = 4, main = "PCNM 7 (May)")
ordisurf(XY_KL10, scores(KL10, choi=10), bubble = 4, main = "PCNM 10 (May)")
ordisurf(XY_KL10, scores(KL10, choi=17), bubble = 4, main = "PCNM 17 (May)")
ordisurf(XY_KL10, scores(KL10, choi=22), bubble = 4, main = "PCNM 22 (May)")
dev.off()

print("LL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/coreM_LL2008_ordiSIG.pdf")
ordisurf(XY_LL, scores(LL, choi=12), bubble = 4, main = "PCNM 12 (May)")
dev.off()

print("SU 2008")
print("No significant core axes")


print("Full")
print("AG 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/AG2008_MordiSIG.pdf")
ordisurf(XY_AG, scores(AG, choi=2), bubble = 4, main = "PCNM 2 (May)")
ordisurf(XY_AG, scores(AG, choi=1), bubble = 4, main = "PCNM 1 (July)")
ordisurf(XY_AG, scores(AG, choi=1), bubble = 4, main = "PCNM 1 (August)")
dev.off()

print("CH 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/CH2008_MordiSIG.pdf")
ordisurf(XY_CH, scores(CH, choi=8), bubble = 4, main = "PCNM 1 (April)")
dev.off()

print("JO 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/JO2008_MordiSIG.pdf")
par(mfrow=c(2,2))
ordisurf(XY_JO, scores(JO, choi=6), bubble = 4, main = "PCNM 6 (May)")
ordisurf(XY_JO, scores(JO, choi=10), bubble = 4, main = "PCNM 10 (May)")
dev.off()


print("KL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/KL2008_MordiSIG.pdf")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (March)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (March)")
ordisurf(XY_KL8, scores(KL8, choi=3), bubble = 4, main = "PCNM 3 (March)")
ordisurf(XY_KL8, scores(KL8, choi=8), bubble = 4, main = "PCNM 8 (March)")
par(mfrow=c(1,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (April)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (April)")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (May)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (May)")
ordisurf(XY_KL8, scores(KL8, choi=5), bubble = 4, main = "PCNM 5 (May)")
ordisurf(XY_KL8, scores(KL8, choi=18), bubble = 4, main = "PCNM 18 (May)")
par(mfrow=c(1,2))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (June)")
ordisurf(XY_KL8, scores(KL8, choi=4), bubble = 4, main = "PCNM 4 (June)")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (August)")
ordisurf(XY_KL8, scores(KL8, choi=3), bubble = 4, main = "PCNM 3 (August)")
ordisurf(XY_KL8, scores(KL8, choi=9), bubble = 4, main = "PCNM 9 (August)")
dev.off()

print("KL 2009")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/KL2009_MordiSIG.pdf")
par(mfrow(1,1))
ordisurf(XY_KL9, scores(KL9, choi=1), bubble = 4, main = "PCNM 1 (April)")
par(mfrow=c(2,2))
ordisurf(XY_KL9, scores(KL9, choi=1), bubble = 4, main = "PCNM 1 (July)")
ordisurf(XY_KL9, scores(KL9, choi=2), bubble = 4, main = "PCNM 2 (July)")
ordisurf(XY_KL9, scores(KL9, choi=3), bubble = 4, main = "PCNM 3 (July)")
ordisurf(XY_KL9, scores(KL9, choi=8), bubble = 4, main = "PCNM 8 (July)")
par(mfrow(1,1))
ordisurf(XY_KL9, scores(KL9, choi=4), bubble = 4, main = "PCNM 4 (August)")
dev.off()

print("KL 2010")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/KL2010_MordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_KL10, scores(KL10, choi=3), bubble = 4, main = "PCNM 3 (February)")
ordisurf(XY_KL10, scores(KL10, choi=4), bubble = 4, main = "PCNM 4 (February)")
par(mfrow=c(3,3))
ordisurf(XY_KL10, scores(KL10, choi=1), bubble = 4, main = "PCNM 1 (March)")
ordisurf(XY_KL10, scores(KL10, choi=2), bubble = 4, main = "PCNM 2 (March)")
ordisurf(XY_KL10, scores(KL10, choi=3), bubble = 4, main = "PCNM 3 (March)")
ordisurf(XY_KL10, scores(KL10, choi=4), bubble = 4, main = "PCNM 4 (March)")
ordisurf(XY_KL10, scores(KL10, choi=5), bubble = 4, main = "PCNM 5 (March)")
ordisurf(XY_KL10, scores(KL10, choi=7), bubble = 4, main = "PCNM 7 (March)")
ordisurf(XY_KL10, scores(KL10, choi=8), bubble = 4, main = "PCNM 8 (March)")
ordisurf(XY_KL10, scores(KL10, choi=9), bubble = 4, main = "PCNM 9 (March)")
ordisurf(XY_KL10, scores(KL10, choi=17), bubble = 4, main = "PCNM 17 (March)")
par(mfrow=c(2,2))
ordisurf(XY_KL10, scores(KL10, choi=2), bubble = 4, main = "PCNM 2 (April)")
ordisurf(XY_KL10, scores(KL10, choi=6), bubble = 4, main = "PCNM 6 (April)")
ordisurf(XY_KL10, scores(KL10, choi=14), bubble = 4, main = "PCNM 14 (April)")
par(mfrow=c(1,1))
ordisurf(XY_KL10, scores(KL10, choi=22), bubble = 4, main = "PCNM 22 (May)")
ordisurf(XY_KL10, scores(KL10, choi=1), bubble = 4, main = "PCNM 1 (June)")
dev.off()

print("LL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/LL2008_MordiSIG.pdf")
ordisurf(XY_LL, scores(LL, choi=1), bubble = 4, main = "PCNM 1 (April)")
ordisurf(XY_LL, scores(LL, choi=9), bubble = 4, main = "PCNM 9 (May)")
dev.off()

print("SU 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/SU2008_MordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_SU, scores(SU, choi=1), bubble = 4, main = "PCNM 1 (May)")
ordisurf(XY_SU, scores(SU, choi=10), bubble = 4, main = "PCNM 10 (May)")
dev.off()

print("Rare")
print("AG 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_AG2008_ordiSIG.pdf")
ordisurf(XY_AG, scores(AG, choi=2), bubble = 4, main = "PCNM 2 (May)")
ordisurf(XY_AG, scores(AG, choi=2), bubble = 4, main = "PCNM 2 (June)")
par(mfrow=c(2,2))
ordisurf(XY_AG, scores(AG, choi=1), bubble = 4, main = "PCNM 1 (July)")
ordisurf(XY_AG, scores(AG, choi=11), bubble = 4, main = "PCNM 11 (July)")
ordisurf(XY_AG, scores(AG, choi=26), bubble = 4, main = "PCNM 26 (July)")
dev.off()

print("CH 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_CH2008_ordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_CH, scores(CH, choi=8), bubble = 4, main = "PCNM 1 (April)")
ordisurf(XY_CH, scores(CH, choi=4), bubble = 4, main = "PCNM 4 (April)")
par(mfrow=c(1,1))
ordisurf(XY_CH, scores(CH, choi=8), bubble = 4, main = "PCNM 1 (May)")
dev.off()

print("JO 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_JO2008_ordiSIG.pdf")
par(mfrow=c(2,2))
ordisurf(XY_JO, scores(JO, choi=6), bubble = 4, main = "PCNM 6 (May)")
ordisurf(XY_JO, scores(JO, choi=10), bubble = 4, main = "PCNM 10 (May)")
dev.off()

print("KL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_KL2008_ordiSIG.pdf")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (March)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (March)")
ordisurf(XY_KL8, scores(KL8, choi=3), bubble = 4, main = "PCNM 3 (March)")
ordisurf(XY_KL8, scores(KL8, choi=8), bubble = 4, main = "PCNM 8 (March)")
par(mfrow=c(1,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (April)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (April)")
par(mfrow=c(5,2))
ordisurf(XY_KL8, scores(KL8, choi=1), bubble = 4, main = "PCNM 1 (May)")
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (May)")
ordisurf(XY_KL8, scores(KL8, choi=5), bubble = 4, main = "PCNM 5 (May)")
ordisurf(XY_KL8, scores(KL8, choi=8), bubble = 4, main = "PCNM 8 (May)")
ordisurf(XY_KL8, scores(KL8, choi=17), bubble = 4, main = "PCNM 17 (May)")
ordisurf(XY_KL8, scores(KL8, choi=18), bubble = 4, main = "PCNM 18 (May)")
ordisurf(XY_KL8, scores(KL8, choi=26), bubble = 4, main = "PCNM 26 (May)")
ordisurf(XY_KL8, scores(KL8, choi=27), bubble = 4, main = "PCNM 27 (May)")
ordisurf(XY_KL8, scores(KL8, choi=34), bubble = 4, main = "PCNM 34 (May)")
ordisurf(XY_KL8, scores(KL8, choi=35), bubble = 4, main = "PCNM 35 (May)")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (June)")
ordisurf(XY_KL8, scores(KL8, choi=4), bubble = 4, main = "PCNM 4 (June)")
ordisurf(XY_KL8, scores(KL8, choi=7), bubble = 4, main = "PCNM 7 (June)")
par(mfrow=c(2,2))
ordisurf(XY_KL8, scores(KL8, choi=2), bubble = 4, main = "PCNM 2 (August)")
ordisurf(XY_KL8, scores(KL8, choi=3), bubble = 4, main = "PCNM 3 (August)")
ordisurf(XY_KL8, scores(KL8, choi=9), bubble = 4, main = "PCNM 9 (August)")
dev.off()

print("KL 2009")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_KL2009_ordiSIG.pdf")
par(mfrow(1,1))
ordisurf(XY_KL9, scores(KL9, choi=6), bubble = 4, main = "PCNM 6 (March)")
ordisurf(XY_KL9, scores(KL9, choi=1), bubble = 4, main = "PCNM 1 (April)")
par(mfrow=c(2,2))
ordisurf(XY_KL9, scores(KL9, choi=1), bubble = 4, main = "PCNM 1 (July)")
ordisurf(XY_KL9, scores(KL9, choi=2), bubble = 4, main = "PCNM 2 (July)")
ordisurf(XY_KL9, scores(KL9, choi=3), bubble = 4, main = "PCNM 3 (July)")
ordisurf(XY_KL9, scores(KL9, choi=8), bubble = 4, main = "PCNM 8 (July)")
par(mfrow(1,1))
ordisurf(XY_KL9, scores(KL9, choi=4), bubble = 4, main = "PCNM 4 (August)")
dev.off()

print("KL 2010")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_KL2010_ordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_KL10, scores(KL10, choi=3), bubble = 4, main = "PCNM 3 (February)")
ordisurf(XY_KL10, scores(KL10, choi=4), bubble = 4, main = "PCNM 4 (February)")
par(mfrow=c(3,3))
ordisurf(XY_KL10, scores(KL10, choi=1), bubble = 4, main = "PCNM 1 (March)")
ordisurf(XY_KL10, scores(KL10, choi=2), bubble = 4, main = "PCNM 2 (March)")
ordisurf(XY_KL10, scores(KL10, choi=3), bubble = 4, main = "PCNM 3 (March)")
ordisurf(XY_KL10, scores(KL10, choi=4), bubble = 4, main = "PCNM 4 (March)")
ordisurf(XY_KL10, scores(KL10, choi=5), bubble = 4, main = "PCNM 5 (March)")
ordisurf(XY_KL10, scores(KL10, choi=7), bubble = 4, main = "PCNM 7 (March)")
ordisurf(XY_KL10, scores(KL10, choi=8), bubble = 4, main = "PCNM 8 (March)")
ordisurf(XY_KL10, scores(KL10, choi=9), bubble = 4, main = "PCNM 9 (March)")
ordisurf(XY_KL10, scores(KL10, choi=17), bubble = 4, main = "PCNM 17 (March)")
par(mfrow=c(2,2))
ordisurf(XY_KL10, scores(KL10, choi=2), bubble = 4, main = "PCNM 2 (April)")
ordisurf(XY_KL10, scores(KL10, choi=6), bubble = 4, main = "PCNM 6 (April)")
ordisurf(XY_KL10, scores(KL10, choi=14), bubble = 4, main = "PCNM 14 (April)")
par(mfrow=c(1,1))
ordisurf(XY_KL10, scores(KL10, choi=22), bubble = 4, main = "PCNM 22 (May)")
ordisurf(XY_KL10, scores(KL10, choi=3), bubble = 4, main = "PCNM 3 (June)")
dev.off()

print("LL 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_LL2008_ordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_LL, scores(LL, choi=1), bubble = 4, main = "PCNM 1 (April)")
ordisurf(XY_LL, scores(LL, choi=4), bubble = 4, main = "PCNM 4 (April)")
par(mfrow=c(1,1))
ordisurf(XY_LL, scores(LL, choi=9), bubble = 4, main = "PCNM 9 (May)")
dev.off()

print("SU 2008")
pdf(file = "/home/ahalhed/red-squirrel-w2020/R-env/RedSquirrelSpatial/plots/rareM_SU2008_ordiSIG.pdf")
par(mfrow=c(1,2))
ordisurf(XY_SU, scores(SU, choi=1), bubble = 4, main = "PCNM 1 (May)")
ordisurf(XY_SU, scores(SU, choi=10), bubble = 4, main = "PCNM 10 (May)")
dev.off()